### ISSUE TITLE
Update hy version to 0.26

### ISSUE THREAD

**Issue by f3zhead-alt** [Arkelis/hyccup#16]
Hello,

First of all thanks for making this project, it's very useful.
Recently [hy v0.26](https://github.com/hylang/hy/releases/tag/0.26.0) was released. I looked at hyccup's code and I think it doesn't break anything (although I'm pretty new to Hy and Lisp in general). Is it possible to bump hy to 0.26?

Thanks,
Franklin Liu

**Comment by Arkelis** [comment]
Hello, a new version of Hyccup was published with Hy updated to v0.26 :)

**Comment by f3zhead-alt** [comment]
Thank you!
